name: Compile Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner to build the .exe file

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Compile the Python script into an EXE
      - name: Compile Python script to EXE
        run: |
          pyinstaller --onefile update.py

      # Upload the EXE artifact
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-exe
          path: update.exe  # Ensure this matches the output path of your EXE

      # Optional: Clean up generated files (you can remove this if you want to keep the build artifacts)
      - name: Clean up build files
        run: |
          rmdir /s /q dist
          rmdir /s /q build
          del /q your_script.spec
